version: "3"
services:
  app:
    build: ./server
    command: npm run start
    ports:
      - "4000:4000"
    environment:
      - APP_SECRET=${APP_SECRET}
      - DB_DEV_HOST=${DB_HOST}
      - DB_DEV_NAME=${DB_NAME}
      - DB_DEV_USERNAME=${DB_USERNAME}
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: mysql:5
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
